// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TopRPM;
lv_obj_t * ui_RPM7;
lv_obj_t * ui_RPM6;
lv_obj_t * ui_RPM8;
lv_obj_t * ui_RPM9;
lv_obj_t * ui_RPM10;
lv_obj_t * ui_RPM;
lv_obj_t * ui_RPM11;
lv_obj_t * ui_RPM12;
lv_obj_t * ui_RPM13;
lv_obj_t * ui_RPM14;
lv_obj_t * ui_RPM5;
lv_obj_t * ui_RPMText;
lv_obj_t * ui_RPMText11;
lv_obj_t * ui_RPMText13;
lv_obj_t * ui_RPMText12;
lv_obj_t * ui_RPMText10;
lv_obj_t * ui_RPMText14;
lv_obj_t * ui_RPMText9;
lv_obj_t * ui_RPMText6;
lv_obj_t * ui_RPMText5;
lv_obj_t * ui_RPMText7;
lv_obj_t * ui_RPMText8;
lv_obj_t * ui_Container3;
lv_obj_t * ui_ZEIT;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Sektor1Static;
lv_obj_t * ui_Sektor1Time;
lv_obj_t * ui_Sektor2Static;
lv_obj_t * ui_Sektor2Time;
lv_obj_t * ui_Sektor3Static;
lv_obj_t * ui_Sektor3Time;
lv_obj_t * ui_CurrentGapStatic;
lv_obj_t * ui_CurrentGapTime;
lv_obj_t * ui_LastLapStatic;
lv_obj_t * ui_LastLapTime;
lv_obj_t * ui_BestLapTime;
lv_obj_t * ui_BestLapStatic;
lv_obj_t * ui_Speed;
lv_obj_t * ui_Gear;
lv_obj_t * ui_RaceboxBatteryStatusStaticPlusTime;
lv_obj_t * ui_RaceboxConnection;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Debug;
lv_obj_t * ui_Debug1;
lv_obj_t * ui_Debug2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
