// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TopRPM;
extern lv_obj_t * ui_RPM7;
extern lv_obj_t * ui_RPM6;
extern lv_obj_t * ui_RPM8;
extern lv_obj_t * ui_RPM9;
extern lv_obj_t * ui_RPM10;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_RPM11;
extern lv_obj_t * ui_RPM12;
extern lv_obj_t * ui_RPM13;
extern lv_obj_t * ui_RPM14;
extern lv_obj_t * ui_RPM5;
extern lv_obj_t * ui_RPMText;
extern lv_obj_t * ui_RPMText11;
extern lv_obj_t * ui_RPMText13;
extern lv_obj_t * ui_RPMText12;
extern lv_obj_t * ui_RPMText10;
extern lv_obj_t * ui_RPMText14;
extern lv_obj_t * ui_RPMText9;
extern lv_obj_t * ui_RPMText6;
extern lv_obj_t * ui_RPMText5;
extern lv_obj_t * ui_RPMText7;
extern lv_obj_t * ui_RPMText8;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_ZEIT;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Sektor1Static;
extern lv_obj_t * ui_Sektor1Time;
extern lv_obj_t * ui_Sektor2Static;
extern lv_obj_t * ui_Sektor2Time;
extern lv_obj_t * ui_Sektor3Static;
extern lv_obj_t * ui_Sektor3Time;
extern lv_obj_t * ui_CurrentGapStatic;
extern lv_obj_t * ui_CurrentGapTime;
extern lv_obj_t * ui_LastLapStatic;
extern lv_obj_t * ui_LastLapTime;
extern lv_obj_t * ui_BestLapTime;
extern lv_obj_t * ui_BestLapStatic;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_Gear;
extern lv_obj_t * ui_RaceboxBatteryStatusStaticPlusTime;
extern lv_obj_t * ui_RaceboxConnection;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Debug;
extern lv_obj_t * ui_Debug1;
extern lv_obj_t * ui_Debug2;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
